# ~/.config/starship.toml

#aliases

#ShellAlliases = {

#sudo =  "doas";
#cat =   "bat";
#music = "ncmpcpp";
#ytdl =  "youtube-dl";
#};


add_newline = true

#[python]
#disabled = true


#[nodejs]
#disabled = true

[battery]
full_symbol = "🔋 "
charging_symbol = " "
discharging_symbol = "💀 "



[[battery.display]]
threshold = 30
style = "bold red"



[[battery.display]]
threshold = 60
style = "bold yellow"



[[battery.display]]
threshold = 100
style = "bold blue"



#[time]
#disabled = false
#format = '[\[ $time \]]($style) '
#time_format = "%T"
#utc_time_offset = "+8"
#time_range = "10:00:00-14:00:00"



[jobs]
symbol = "+ "
threshold = 4



[git_branch]
symbol = " "
